#!/bin/sh
#
#PROVIDE: minecraft

. /etc/rc.subr

name="mcmyadmin"
rcvar="mc_enable"
start_cmd="mc_start"
stop_cmd="mc_stop"
restart_cmd="mc_restart"
update_cmd="mc_update"
status_cmd="mc_status"

#Settings
SERVICE='McMyAdmin.exe'
USERNAME="minecraft"
MCPATH='/srv/minecraft'
ME=`whoami`

load_rc_config ${name}

as_user() {
  if [ "$ME" == "$USERNAME" ]; then
    sh -c "$1"
  else
    su $USERNAME -c "$1"
  fi
}

mc_start() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
    then
      echo "Tried to start but $SERVICE was already running!"
    else
      echo "$SERVICE was not running... starting."
      cd $MCPATH
      as_user "cd $MCPATH && screen -dmS minecraft mono McMyAdmin.exe"
      sleep 7
      if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
        then
          echo "$SERVICE is now running."
        else
          echo "Could not start $SERVICE"
      fi
  fi
}

mc_stop() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
    then
      echo "$SERVICE is running... stopping."
      sleep 7
      # broadcast shutdown notification to players
      as_user "screen -p 0 -S minecraft -X eval 'stuff \"say SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...\"\015'"
      # save the world
      as_user "screen -p 0 -S minecraft -X eval 'stuff \"save-all\"\015'"
      sleep 10
      # send McMyAdmin console the /quit command
      as_user "screen -p 0 -S minecraft -X eval 'stuff \"/quit\"\015'"
      sleep 7
    else
      echo "$SERVICE was not running."
  fi
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
    then
      echo "$SERVICE could not be shut down... still running"
    else
      echo "$SERVICE is shut down."
  fi
}

mc_restart() {
  mc_stop
  sleep 1
  mc_start
}

mc_update() {
  as_user "screen -p 0 -S minecraft -X eval 'stuff \"say SERVER GOING DOWN FOR UPDATE IN 10 SECS!\"\015'"
  sleep 10
  as_user "screen -p 0 -S minecraft -X eval 'stuff \"/update\"\015'"
  echo "Sent /update command to $SERVICE"
}

mc_status() {
  if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
    then
      echo "$SERVICE is running."
    else
      echo "$SERVICE is not running."
  fi
}

run_rc_command "$1"
